# copydatabase
# Autogenerated from man page /usr/share/man/man1/copydatabase.1.gz
complete -c copydatabase -l no-renumber -d 'Preserve the numbering of document ids (useful if you have external reference…'
complete -c copydatabase -l help -d 'display this help and exit'
complete -c copydatabase -l version -d 'output version information and exit'

