# font-manager
# Autogenerated from man page /usr/share/man/man1/font-manager.1.gz
complete -c font-manager -s a -l about -d 'About the application'
complete -c font-manager -s v -l version -d 'Show application version'
complete -c font-manager -s l -l list -d 'List available font families'
complete -c font-manager -l list-full -d 'Full listing including face information (JSON)'
complete -c font-manager -s e -l enable -d 'Space separated list of font families to enable'
complete -c font-manager -s d -l disable -d 'Space separated list of font families to disable'
complete -c font-manager -s i -l install -d 'Space separated list of files to install'
complete -c font-manager -s u -l update -d 'Update application database FILES'

