# gh-codespace-logs
# Autogenerated from man page /usr/share/man/man1/gh-codespace-logs.1.gz
complete -c gh-codespace-logs -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-logs -s f -l follow -d 'Tail and follow the logs SEE ALSO'

