# gh-codespace-code
# Autogenerated from man page /usr/share/man/man1/gh-codespace-code.1.gz
complete -c gh-codespace-code -s c -l codespace -d 'Name of the codespace'
complete -c gh-codespace-code -l insiders -d 'Use the insiders version of Visual Studio Code SEE ALSO'

