# gh-codespace-ports-visibility
# Autogenerated from man page /usr/share/man/man1/gh-codespace-ports-visibility.1.gz
complete -c gh-codespace-ports-visibility -s c -l codespace -d 'Name of the codespace EXAMPLE gh codespace ports visibility 80:org 3000:priva…'

