# gh-release-download
# Autogenerated from man page /usr/share/man/man1/gh-release-download.1.gz
complete -c gh-release-download -s A -l archive -d 'Download the source code archive in the specified format (zip or tar. gz)'
complete -c gh-release-download -s D -l dir -d 'The directory to download files into'
complete -c gh-release-download -s p -l pattern -d 'Download only assets that match a glob pattern OPTIONS INHERITED FROM PARENT …'
complete -c gh-release-download -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format EXAMPLE # downlo…'

