# gh-repo-rename
# Autogenerated from man page /usr/share/man/man1/gh-repo-rename.1.gz
complete -c gh-repo-rename -s y -l confirm -d 'skip confirmation prompt'
complete -c gh-repo-rename -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

