# gh-secret-remove
# Autogenerated from man page /usr/share/man/man1/gh-secret-remove.1.gz
complete -c gh-secret-remove -s e -l env -d 'Remove a secret for an environment'
complete -c gh-secret-remove -s o -l org -d 'Remove a secret for an organization'
complete -c gh-secret-remove -s u -l user -d 'Remove a secret for your user OPTIONS INHERITED FROM PARENT COMMANDS'
complete -c gh-secret-remove -s R -l repo -d 'Select another repository using the [HOST/]OWNER/REPO format SEE ALSO'

