# imv
# Autogenerated from man page /usr/share/man/man1/imv.1.gz
complete -c imv -s h -d 'Show help message and quit'
complete -c imv -s v -d 'Show version and quit'
complete -c imv -s b -d 'Set the background colour'
complete -c imv -s c -d 'Specify a command to be run on launch, after the configuration has been loaded'
complete -c imv -s d -d 'Start with overlay visible'
complete -c imv -s f -d 'Start fullscreen'
complete -c imv -s l -d 'List open files to stdout at exit'
complete -c imv -s n -d 'Start with the given path, or index selected'
complete -c imv -s r -d 'Load directories recursively'
complete -c imv -s s -d 'Set scaling mode to use.  none will show each image at its actual size'
complete -c imv -s t -d 'Start in slideshow mode, with each image shown for the given number of seconds'
complete -c imv -s u -d 'Set upscaling method used by imv'
complete -c imv -s x -d 'Disable looping of input paths'
complete -c imv -s 1
complete -c imv -s 2 -d 'g.  zoom <amount|actual>'

