# kccachetest
# Autogenerated from man page /usr/share/man/man1/kccachetest.1.gz
complete -c kccachetest -o th
complete -c kccachetest -o rnd
complete -c kccachetest -o etc
complete -c kccachetest -o tran
complete -c kccachetest -o tc
complete -c kccachetest -o bnum
complete -c kccachetest -o capcnt
complete -c kccachetest -o capsiz
complete -c kccachetest -o lv
complete -c kccachetest -o it -d 'This command returns 0 on success, another on failure'

