# kcdirtest
# Autogenerated from man page /usr/share/man/man1/kcdirtest.1.gz
complete -c kcdirtest -o th
complete -c kcdirtest -o rnd
complete -c kcdirtest -o set
complete -c kcdirtest -o get
complete -c kcdirtest -o getw
complete -c kcdirtest -o rem
complete -c kcdirtest -o etc
complete -c kcdirtest -o tran
complete -c kcdirtest -o oat
complete -c kcdirtest -o oas
complete -c kcdirtest -o onl
complete -c kcdirtest -o otl
complete -c kcdirtest -o onr
complete -c kcdirtest -o tc
complete -c kcdirtest -o lv
complete -c kcdirtest -o it
complete -c kcdirtest -o hard -d 'This command returns 0 on success, another on failure'

