# kcdirmgr
# Autogenerated from man page /usr/share/man/man1/kcdirmgr.1.gz
complete -c kcdirmgr -o otr
complete -c kcdirmgr -o onl
complete -c kcdirmgr -o otl
complete -c kcdirmgr -o onr
complete -c kcdirmgr -o tc
complete -c kcdirmgr -o st
complete -c kcdirmgr -o add
complete -c kcdirmgr -o app
complete -c kcdirmgr -o rep
complete -c kcdirmgr -o inci
complete -c kcdirmgr -o incd
complete -c kcdirmgr -o sx
complete -c kcdirmgr -o rm
complete -c kcdirmgr -o px
complete -c kcdirmgr -o pz
complete -c kcdirmgr -o max
complete -c kcdirmgr -o pv -d 'This command returns 0 on success, another on failure'

