# kcforestmgr
# Autogenerated from man page /usr/share/man/man1/kcforestmgr.1.gz
complete -c kcforestmgr -o otr
complete -c kcforestmgr -o onl
complete -c kcforestmgr -o otl
complete -c kcforestmgr -o onr
complete -c kcforestmgr -o tc
complete -c kcforestmgr -o bnum
complete -c kcforestmgr -o psiz
complete -c kcforestmgr -o rcd
complete -c kcforestmgr -o rcld
complete -c kcforestmgr -o rcdd
complete -c kcforestmgr -o st
complete -c kcforestmgr -o add
complete -c kcforestmgr -o app
complete -c kcforestmgr -o rep
complete -c kcforestmgr -o inci
complete -c kcforestmgr -o incd
complete -c kcforestmgr -o sx
complete -c kcforestmgr -o rm
complete -c kcforestmgr -o px
complete -c kcforestmgr -o pz
complete -c kcforestmgr -o des
complete -c kcforestmgr -o max
complete -c kcforestmgr -o pv -d 'This command returns 0 on success, another on failure'

