# kcforesttest
# Autogenerated from man page /usr/share/man/man1/kcforesttest.1.gz
complete -c kcforesttest -o th
complete -c kcforesttest -o rnd
complete -c kcforesttest -o set
complete -c kcforesttest -o get
complete -c kcforesttest -o getw
complete -c kcforesttest -o rem
complete -c kcforesttest -o etc
complete -c kcforesttest -o tran
complete -c kcforesttest -o oat
complete -c kcforesttest -o oas
complete -c kcforesttest -o onl
complete -c kcforesttest -o otl
complete -c kcforesttest -o onr
complete -c kcforesttest -o tc
complete -c kcforesttest -o bnum
complete -c kcforesttest -o psiz
complete -c kcforesttest -o pccap
complete -c kcforesttest -o rcd
complete -c kcforesttest -o rcld
complete -c kcforesttest -o rcdd
complete -c kcforesttest -o lv
complete -c kcforesttest -o it
complete -c kcforesttest -o hard -d 'This command returns 0 on success, another on failure'

