# kcgrasstest
# Autogenerated from man page /usr/share/man/man1/kcgrasstest.1.gz
complete -c kcgrasstest -o th
complete -c kcgrasstest -o rnd
complete -c kcgrasstest -o etc
complete -c kcgrasstest -o tran
complete -c kcgrasstest -o tc
complete -c kcgrasstest -o bnum
complete -c kcgrasstest -o psiz
complete -c kcgrasstest -o pccap
complete -c kcgrasstest -o rcd
complete -c kcgrasstest -o rcld
complete -c kcgrasstest -o rcdd
complete -c kcgrasstest -o lv
complete -c kcgrasstest -o it -d 'This command returns 0 on success, another on failure'

