# kchashmgr
# Autogenerated from man page /usr/share/man/man1/kchashmgr.1.gz
complete -c kchashmgr -o otr
complete -c kchashmgr -o onl
complete -c kchashmgr -o otl
complete -c kchashmgr -o onr
complete -c kchashmgr -o apow
complete -c kchashmgr -o fpow
complete -c kchashmgr -o ts
complete -c kchashmgr -o tl
complete -c kchashmgr -o tc
complete -c kchashmgr -o bnum
complete -c kchashmgr -o st
complete -c kchashmgr -o add
complete -c kchashmgr -o app
complete -c kchashmgr -o rep
complete -c kchashmgr -o inci
complete -c kchashmgr -o incd
complete -c kchashmgr -o sx
complete -c kchashmgr -o rm
complete -c kchashmgr -o px
complete -c kchashmgr -o pz
complete -c kchashmgr -o max
complete -c kchashmgr -o pv -d 'This command returns 0 on success, another on failure'

