# kchashtest
# Autogenerated from man page /usr/share/man/man1/kchashtest.1.gz
complete -c kchashtest -o th
complete -c kchashtest -o rnd
complete -c kchashtest -o set
complete -c kchashtest -o get
complete -c kchashtest -o getw
complete -c kchashtest -o rem
complete -c kchashtest -o etc
complete -c kchashtest -o tran
complete -c kchashtest -o oat
complete -c kchashtest -o oas
complete -c kchashtest -o onl
complete -c kchashtest -o otl
complete -c kchashtest -o onr
complete -c kchashtest -o apow
complete -c kchashtest -o fpow
complete -c kchashtest -o ts
complete -c kchashtest -o tl
complete -c kchashtest -o tc
complete -c kchashtest -o bnum
complete -c kchashtest -o msiz
complete -c kchashtest -o dfunit
complete -c kchashtest -o lv
complete -c kchashtest -o it
complete -c kchashtest -o hard -d 'This command returns 0 on success, another on failure'

