# kclangctest
# Autogenerated from man page /usr/share/man/man1/kclangctest.1.gz
complete -c kclangctest -o rnd
complete -c kclangctest -o etc
complete -c kclangctest -o tran
complete -c kclangctest -o oat
complete -c kclangctest -o oas
complete -c kclangctest -o onl
complete -c kclangctest -o otl
complete -c kclangctest -o onr
complete -c kclangctest -o bnum -d 'This command returns 0 on success, another on failure'

