# kcpolytest
# Autogenerated from man page /usr/share/man/man1/kcpolytest.1.gz
complete -c kcpolytest -o th
complete -c kcpolytest -o rnd
complete -c kcpolytest -o set
complete -c kcpolytest -o get
complete -c kcpolytest -o getw
complete -c kcpolytest -o rem
complete -c kcpolytest -o etc
complete -c kcpolytest -o tran
complete -c kcpolytest -o oat
complete -c kcpolytest -o oas
complete -c kcpolytest -o onl
complete -c kcpolytest -o otl
complete -c kcpolytest -o onr
complete -c kcpolytest -o lv
complete -c kcpolytest -o it
complete -c kcpolytest -o hard
complete -c kcpolytest -o ru
complete -c kcpolytest -o tmp
complete -c kcpolytest -o dbnum
complete -c kcpolytest -o clim
complete -c kcpolytest -o cbnum
complete -c kcpolytest -o xnl
complete -c kcpolytest -o xpm
complete -c kcpolytest -o xpr
complete -c kcpolytest -o xpf
complete -c kcpolytest -o xnc -d 'This command returns 0 on success, another on failure'

