# kcpolymgr
# Autogenerated from man page /usr/share/man/man1/kcpolymgr.1.gz
complete -c kcpolymgr -o otr
complete -c kcpolymgr -o onl
complete -c kcpolymgr -o otl
complete -c kcpolymgr -o onr
complete -c kcpolymgr -o st
complete -c kcpolymgr -o add
complete -c kcpolymgr -o app
complete -c kcpolymgr -o rep
complete -c kcpolymgr -o inci
complete -c kcpolymgr -o incd
complete -c kcpolymgr -o sx
complete -c kcpolymgr -o rm
complete -c kcpolymgr -o px
complete -c kcpolymgr -o pz
complete -c kcpolymgr -o mp
complete -c kcpolymgr -o mr
complete -c kcpolymgr -o ms
complete -c kcpolymgr -o des
complete -c kcpolymgr -o max
complete -c kcpolymgr -o pv -d 'This command returns 0 on success, another on failure'

