# kcprototest
# Autogenerated from man page /usr/share/man/man1/kcprototest.1.gz
complete -c kcprototest -o tree
complete -c kcprototest -o th
complete -c kcprototest -o rnd
complete -c kcprototest -o etc
complete -c kcprototest -o tran
complete -c kcprototest -o it -d 'This command returns 0 on success, another on failure'

