# kcstashtest
# Autogenerated from man page /usr/share/man/man1/kcstashtest.1.gz
complete -c kcstashtest -o th
complete -c kcstashtest -o rnd
complete -c kcstashtest -o etc
complete -c kcstashtest -o tran
complete -c kcstashtest -o bnum
complete -c kcstashtest -o lv
complete -c kcstashtest -o it -d 'This command returns 0 on success, another on failure'

