# kctreetest
# Autogenerated from man page /usr/share/man/man1/kctreetest.1.gz
complete -c kctreetest -o th
complete -c kctreetest -o rnd
complete -c kctreetest -o set
complete -c kctreetest -o get
complete -c kctreetest -o getw
complete -c kctreetest -o rem
complete -c kctreetest -o etc
complete -c kctreetest -o tran
complete -c kctreetest -o oat
complete -c kctreetest -o oas
complete -c kctreetest -o onl
complete -c kctreetest -o otl
complete -c kctreetest -o onr
complete -c kctreetest -o apow
complete -c kctreetest -o fpow
complete -c kctreetest -o ts
complete -c kctreetest -o tl
complete -c kctreetest -o tc
complete -c kctreetest -o bnum
complete -c kctreetest -o psiz
complete -c kctreetest -o msiz
complete -c kctreetest -o dfunit
complete -c kctreetest -o pccap
complete -c kctreetest -o rcd
complete -c kctreetest -o rcld
complete -c kctreetest -o rcdd
complete -c kctreetest -o lv
complete -c kctreetest -o it
complete -c kctreetest -o hard -d 'This command returns 0 on success, another on failure'

