# kctreemgr
# Autogenerated from man page /usr/share/man/man1/kctreemgr.1.gz
complete -c kctreemgr -o otr
complete -c kctreemgr -o onl
complete -c kctreemgr -o otl
complete -c kctreemgr -o onr
complete -c kctreemgr -o apow
complete -c kctreemgr -o fpow
complete -c kctreemgr -o ts
complete -c kctreemgr -o tl
complete -c kctreemgr -o tc
complete -c kctreemgr -o bnum
complete -c kctreemgr -o psiz
complete -c kctreemgr -o rcd
complete -c kctreemgr -o rcld
complete -c kctreemgr -o rcdd
complete -c kctreemgr -o st
complete -c kctreemgr -o add
complete -c kctreemgr -o app
complete -c kctreemgr -o rep
complete -c kctreemgr -o inci
complete -c kctreemgr -o incd
complete -c kctreemgr -o sx
complete -c kctreemgr -o rm
complete -c kctreemgr -o px
complete -c kctreemgr -o pz
complete -c kctreemgr -o des
complete -c kctreemgr -o max
complete -c kctreemgr -o pv -d 'This command returns 0 on success, another on failure'

