# kcutiltest
# Autogenerated from man page /usr/share/man/man1/kcutiltest.1.gz
complete -c kcutiltest -o th
complete -c kcutiltest -o iv
complete -c kcutiltest -o rnd
complete -c kcutiltest -o msiz
complete -c kcutiltest -o bnum -d 'This command returns 0 on success, another on failure'

