# kcutilmgr
# Autogenerated from man page /usr/share/man/man1/kcutilmgr.1.gz
complete -c kcutilmgr -s d
complete -c kcutilmgr -o hex
complete -c kcutilmgr -o url
complete -c kcutilmgr -o quote
complete -c kcutilmgr -o key
complete -c kcutilmgr -o def
complete -c kcutilmgr -o gz
complete -c kcutilmgr -o lzo
complete -c kcutilmgr -o lzma
complete -c kcutilmgr -o fnv
complete -c kcutilmgr -o path
complete -c kcutilmgr -o crc
complete -c kcutilmgr -o alt
complete -c kcutilmgr -o ic
complete -c kcutilmgr -s v
complete -c kcutilmgr -s i
complete -c kcutilmgr -s l
complete -c kcutilmgr -s p -d 'This command returns 0 on success, another on failure'

