# newsboat
# Autogenerated from man page /usr/share/man/man1/newsboat.1.gz
complete -c newsboat -s h -l help
complete -c newsboat -s r -l refresh-on-start
complete -c newsboat -s e -l export-to-opml
complete -c newsboat -s X -l vacuum
complete -c newsboat -l cleanup
complete -c newsboat -s v -s V -l version
complete -c newsboat -s i -l import-from-opml
complete -c newsboat -s u -l url-file
complete -c newsboat -s c -l cache-file
complete -c newsboat -s C -l config-file
complete -c newsboat -s x -l execute
complete -c newsboat -s l -l log-level
complete -c newsboat -s d -l log-file
complete -c newsboat -s E -l export-to-file
complete -c newsboat -s I -l import-from-file

