# notmuch
# Autogenerated from man page /usr/share/man/man1/notmuch.1.gz
complete -c notmuch -l help -d 'Print a synopsis of available commands and exit'
complete -c notmuch -l version -d 'Print the installed version of notmuch, and exit'
complete -c notmuch -l config -d 'Specify the configuration file to use'
complete -c notmuch -l uuid -d 'Enforce that the database UUID (a unique identifier which persists until e. g'

