# notmuch-count
# Autogenerated from man page /usr/share/man/man1/notmuch-count.1.gz
complete -c notmuch-count -l output -d 'NDENT 7. 0'
complete -c notmuch-count -l exclude -d 'Specify whether to omit messages matching search'
complete -c notmuch-count -l batch -d 'Read queries from a file (stdin by default), one per line, and output the num…'
complete -c notmuch-count -l lastmod -d 'Append lastmod (counter for number of database updates) and UUID to the output'
complete -c notmuch-count -l input -d 'Read input from given file, instead of from stdin.  Implies'

