# notmuch-address
# Autogenerated from man page /usr/share/man/man1/notmuch-address.1.gz
complete -c notmuch-address -l format -d 'Presents the results in either JSON, S-Expressions, newline character separat…'
complete -c notmuch-address -l format-version -d 'Use the specified structured output format version'
complete -c notmuch-address -l output -d 'Controls which information appears in the output'
complete -c notmuch-address -l deduplicate -d 'Control the deduplication of results.  NDENT 7. 0'
complete -c notmuch-address -l sort -d 'This option can be used to present results in either chronological order (old…'
complete -c notmuch-address -l exclude -d 'A message is called "excluded" if it matches at least one tag in search'

