# notmuch-compact
# Autogenerated from man page /usr/share/man/man1/notmuch-compact.1.gz
complete -c notmuch-compact -l backup -d 'Save the current database to the given directory before replacing it with the…'
complete -c notmuch-compact -l quiet -d 'Do not report database compaction progress to stdout'

