# notmuch-new
# Autogenerated from man page /usr/share/man/man1/notmuch-new.1.gz
complete -c notmuch-new -l no-hooks -d 'Prevents hooks from being run. UNINDENT NDENT 0. 0'
complete -c notmuch-new -l quiet -d 'Do not print progress or results. UNINDENT NDENT 0. 0'
complete -c notmuch-new -l verbose -d 'Print file names being processed.  Ignored when combined with --quiet'
complete -c notmuch-new -l decrypt -d 'If true, when encountering an encrypted message, try to decrypt it while inde…'
complete -c notmuch-new -l full-scan -d 'By default notmuch-new uses directory modification times (mtimes) to optimize…'

