# notmuch-emacs-mua
# Autogenerated from man page /usr/share/man/man1/notmuch-emacs-mua.1.gz
complete -c notmuch-emacs-mua -s h -l help -d 'Display help. UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -s s -l subject -d 'Specify the subject of the message. UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -l to -d 'Specify a recipient (To). UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -s c -l cc -d 'Specify a carbon-copy (Cc) recipient. UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -s b -l bcc -d 'Specify a blind-carbon-copy (Bcc) recipient. UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -s i -l body -d 'Specify a file to include into the body of the message. UNINDENT NDENT 0. 0'
complete -c notmuch-emacs-mua -l hello -d 'Go to the Notmuch hello screen instead of the message composition window if n…'
complete -c notmuch-emacs-mua -l no-window-system -d 'Even if a window system is available, use the current terminal'
complete -c notmuch-emacs-mua -l client -d 'Use emacsclient(1), rather than emacs(1)'
complete -c notmuch-emacs-mua -l auto-daemon -d 'Automatically start Emacs in daemon mode, if the Emacs server is not running'
complete -c notmuch-emacs-mua -l create-frame -d 'Create a new frame instead of trying to use the current Emacs frame'
complete -c notmuch-emacs-mua -l print -d 'Output the resulting elisp to stdout instead of evaluating it'

