# notmuch-dump
# Autogenerated from man page /usr/share/man/man1/notmuch-dump.1.gz
complete -c notmuch-dump -l gzip -d 'Compress the output in a format compatible with gzip(1). UNINDENT NDENT 0. 0'
complete -c notmuch-dump -l format -d 'Notmuch restore supports two plain text dump formats, both with one message-i…'
complete -c notmuch-dump -l include -d 'Control what kind of metadata is included in the output.  NDENT 7. 0'
complete -c notmuch-dump -l output -d 'Write output to given file instead of stdout'

