# notmuch-reply
# Autogenerated from man page /usr/share/man/man1/notmuch-reply.1.gz
complete -c notmuch-reply -l format -d 'NDENT 7. 0'
complete -c notmuch-reply -l format-version -d 'Use the specified structured output format version'
complete -c notmuch-reply -l reply-to -d 'NDENT 7. 0'
complete -c notmuch-reply -l decrypt -d 'If true, decrypt any MIME encrypted parts found in the selected content (i. e'

