# notmuch-restore
# Autogenerated from man page /usr/share/man/man1/notmuch-restore.1.gz
complete -c notmuch-restore -l accumulate -d 'The union of the existing and new tags is applied, instead of replacing each …'
complete -c notmuch-restore -l format -d 'Notmuch restore supports two plain text dump formats, with each line specifyi…'
complete -c notmuch-restore -l include -d 'Control what kind of metadata is restored.  NDENT 7. 0'
complete -c notmuch-restore -l input -d 'Read input from given file instead of stdin'

