# notmuch-insert
# Autogenerated from man page /usr/share/man/man1/notmuch-insert.1.gz
complete -c notmuch-insert -l folder -d 'Deliver the message to the specified folder, relative to the top-level direct…'
complete -c notmuch-insert -l create-folder -d 'Try to create the folder named by the --folder option, if it does not exist'
complete -c notmuch-insert -l keep -d 'Keep the message file if indexing fails, and keep the message indexed if appl…'
complete -c notmuch-insert -l no-hooks -d 'Prevent hooks from being run. UNINDENT NDENT 0. 0'
complete -c notmuch-insert -l world-readable -d 'When writing mail to the mailbox, allow it to be read by users other than the…'
complete -c notmuch-insert -l decrypt -d 'If true and the message is encrypted, try to decrypt the message while indexi…'

