# notmuch-show
# Autogenerated from man page /usr/share/man/man1/notmuch-show.1.gz
complete -c notmuch-show -l entire-thread -d 'If true, notmuch show outputs all messages in the thread of any message match…'
complete -c notmuch-show -l format -d 'NDENT 7. 0'
complete -c notmuch-show -l part -d 'Write the raw bytes of the given MIME part of a message to standard out'
complete -c notmuch-show -l format-version -d 'Use the specified structured output format version'
complete -c notmuch-show -l sort -d 'This option can be used to present results in either chronological order (old…'
complete -c notmuch-show -l verify -d 'Compute and report the validity of any MIME cryptographic signatures found in…'
complete -c notmuch-show -l decrypt -d 'If true, decrypt any MIME encrypted parts found in the selected content (e. g'
complete -c notmuch-show -l exclude -d 'Specify whether to omit threads only matching search'
complete -c notmuch-show -l body -d 'If true (the default) notmuch show includes the bodies of the messages in the…'
complete -c notmuch-show -l include-html -d 'Include "text/html" parts as part of the output (currently only supported wit…'

