# notmuch-reindex
# Autogenerated from man page /usr/share/man/man1/notmuch-reindex.1.gz
complete -c notmuch-reindex -l decrypt -d 'If true, when encountering an encrypted message, try to decrypt it while rein…'

