# notmuch-search
# Autogenerated from man page /usr/share/man/man1/notmuch-search.1.gz
complete -c notmuch-search -l format -d 'Presents the results in either JSON, S-Expressions, newline character separat…'
complete -c notmuch-search -l format-version -d 'Use the specified structured output format version'
complete -c notmuch-search -l output -d 'NDENT 7. 0'
complete -c notmuch-search -l sort -d 'This option can be used to present results in either chronological order (old…'
complete -c notmuch-search -l offset -d 'Skip displaying the first N results'
complete -c notmuch-search -l limit -d 'Limit the number of displayed results to N. UNINDENT NDENT 0. 0'
complete -c notmuch-search -l exclude -d 'A message is called "excluded" if it matches at least one tag in search'
complete -c notmuch-search -l duplicate -d 'For --output=files, output the Nth filename associated with each message matc…'

