# podboat
# Autogenerated from man page /usr/share/man/man1/podboat.1.gz
complete -c podboat -s h -l help
complete -c podboat -s C -l config-file
complete -c podboat -s q -l queue-file
complete -c podboat -s a -l autodownload
complete -c podboat -s l -l log-level
complete -c podboat -s d -l log-file

