# quest
# Autogenerated from man page /usr/share/man/man1/quest.1.gz
complete -c quest -s d -l db -d 'database to search (multiple databases may be specified)'
complete -c quest -s m -l msize -d 'maximum number of matches to return'
complete -c quest -s c -l check-at-least -d 'minimum number of matches to check'
complete -c quest -s s -l stemmer -d 'set the stemming language, the default is \'english\' (pass \'none\' to disable s…'
complete -c quest -s p -l prefix -d 'add a prefix'
complete -c quest -s b -l boolean-prefix -d 'add a boolean prefix'
complete -c quest -s f -l flags -d 'specify QueryParser flags'
complete -c quest -s o -l default-op -d 'specify QueryParser default operator (default: or)'
complete -c quest -s w -l weight -d 'specify weighting scheme to use (default: bm25)'
complete -c quest -s h -l help -d 'display this help and exit'
complete -c quest -s v -l version -d 'output version information and exit'

