# riverctl
# Autogenerated from man page /home/me/.local/share/man/man1/riverctl.1
complete -c riverctl -s h -d 'Print a help message and exit'
complete -c riverctl -o version -d 'Print the version number and exit'

