# river
# Autogenerated from man page /home/me/.local/share/man/man1/river.1
complete -c river -s h -d 'Print a help message and exit'
complete -c river -o version -d 'Print the version number and exit'
complete -c river -s c -d 'Override the default search paths for an init executable: instead'
complete -c river -o log-level -d 'Set the log level of river.  At the error log level, only errors'

