# rivertile
# Autogenerated from man page /home/me/.local/share/man/man1/rivertile.1
complete -c rivertile -s h -d 'Print a help message and exit'
complete -c rivertile -o version -d 'Print the version number and exit'
complete -c rivertile -o view-padding -d 'Set the padding around views in pixels.  (Default: 6)'
complete -c rivertile -o outer-padding -d 'Set the padding around the edge of the layout area in pixels'
complete -c rivertile -o main-location -d 'Set the initial location of the main area in the layout'
complete -c rivertile -o main-count -d 'Set the initial number of views in the main area of the'
complete -c rivertile -o main-ratio -d 'Set the initial ratio of the main area to total layout area.  The'

