# seatd-launch
# Autogenerated from man page /usr/share/man/man1/seatd-launch.1.gz
complete -c seatd-launch -s h -d 'Show help message and quit'
complete -c seatd-launch -s s -d 'Where to create the seatd socket.  Defaults to a unique file path'
complete -c seatd-launch -s v -d 'Show the version number and quit'

