# transmission-show
# Autogenerated from man page /usr/share/man/man1/transmission-show.1.gz
complete -c transmission-show -s h -d 'Show a short help page and exit'
complete -c transmission-show -s m -d 'Show a magnet link for the specified . torrent file'
complete -c transmission-show -s s -d 'Ask the torrent\'s trackers how many peers are in the torrent\'s swarm El AUTHO…'

