# xapian-delve
# Autogenerated from man page /usr/share/man/man1/xapian-delve.1.gz
complete -c xapian-delve -s a -d 'show all terms in the database'
complete -c xapian-delve -s A -d 'show all terms in the database with given prefix'
complete -c xapian-delve -s r -d 'for term list(s)'
complete -c xapian-delve -s t -d 'for posting list(s)'
complete -c xapian-delve -s s -l stemmer -d 'set the stemming language, the default is \'none\''
complete -c xapian-delve -s 1 -d 'output one list entry per line'
complete -c xapian-delve -o 'V<valueno>' -d 'output value valueno for each document referred to (or each document in the d…'
complete -c xapian-delve -s V -d 'output all values for each document referred to.  <type> is as above'
complete -c xapian-delve -s d -d 'output document data for each document referred to'
complete -c xapian-delve -s z -d 'for db, count documents with length 0'
complete -c xapian-delve -s v -d 'extra info (wdf and len for postlist; wdf and termfreq for termlist; number o…'
complete -c xapian-delve -o vv -d 'even more info (also show collection freq and wdf upper bound for terms)'
complete -c xapian-delve -l help -d 'display this help and exit'
complete -c xapian-delve -l version -d 'output version information and exit'

