# xapian-tcpsrv
# Autogenerated from man page /usr/share/man/man1/xapian-tcpsrv.1.gz
complete -c xapian-tcpsrv -l port -d 'listen on port PORTNUM for connections (no default)'
complete -c xapian-tcpsrv -l interface -d 'listen on the interface associated with name or address ADDRESS (default is a…'
complete -c xapian-tcpsrv -l idle-timeout -d 'set timeout for idle connections (default MSECS_IDLE_TIMEOUT_DEFAULTms)'
complete -c xapian-tcpsrv -l active-timeout -d 'set timeout for active connections (default MSECS_ACTIVE_TIMEOUT_DEFAULTms)'
complete -c xapian-tcpsrv -l timeout -d 'set both timeout values'
complete -c xapian-tcpsrv -l one-shot -d 'serve a single connection and exit'
complete -c xapian-tcpsrv -l quiet -d 'disable information messages to stdout'
complete -c xapian-tcpsrv -l writable -d 'allow updates (only one database directory allowed)'
complete -c xapian-tcpsrv -l help -d 'display this help and exit'
complete -c xapian-tcpsrv -l version -d 'output version information and exit'

