# xapian-progsrv
# Autogenerated from man page /usr/share/man/man1/xapian-progsrv.1.gz
complete -c xapian-progsrv -l timeout -d 'set timeout'
complete -c xapian-progsrv -l writable -d 'allow updates (only one database directory allowed)'
complete -c xapian-progsrv -l help -d 'display this help and exit'
complete -c xapian-progsrv -l version -d 'output version information and exit'

