# xapian-pos
# Autogenerated from man page /usr/share/man/man1/xapian-pos.1.gz
complete -c xapian-pos -s d -l doc -d 'Show positions for document DOCID'
complete -c xapian-pos -s s -l start -d 'Specifies the first position to show'
complete -c xapian-pos -s e -l end -d 'Specifies the last position to show'
complete -c xapian-pos -l help -d 'display this help and exit'
complete -c xapian-pos -l version -d 'output version information and exit'

