# xapian-replicate
# Autogenerated from man page /usr/share/man/man1/xapian-replicate.1.gz
complete -c xapian-replicate -s h -l host -d 'host to connect to (required)'
complete -c xapian-replicate -s p -l port -d 'port to connect to (required)'
complete -c xapian-replicate -s m -l master -d 'replicate database DB from the master (default: DATABASE)'
complete -c xapian-replicate -s i -l interval -d 'wait N seconds between each connection to the master (default: 60)'
complete -c xapian-replicate -s r -l reader-time -d 'applying repeated changesets (default: 30)'
complete -c xapian-replicate -s t -l timeout -d 'set socket timeouts (if supported) to N seconds; N=0 for no timeout (default:…'
complete -c xapian-replicate -s f -l force-copy -d 'force a full copy of the database to be sent (and then replicate as normal)'
complete -c xapian-replicate -s o -l one-shot -d 'replicate only once and then exit'
complete -c xapian-replicate -s q -l quiet -d 'only report errors'
complete -c xapian-replicate -s v -l verbose -d 'be more verbose'
complete -c xapian-replicate -l help -d 'display this help and exit'
complete -c xapian-replicate -l version -d 'output version information and exit'

