# xapian-replicate-server
# Autogenerated from man page /usr/share/man/man1/xapian-replicate-server.1.gz
complete -c xapian-replicate-server -s I -l interface -d 'listen on interface ADDR'
complete -c xapian-replicate-server -s p -l port -d 'port to listen on'
complete -c xapian-replicate-server -s o -l one-shot -d 'serve a single connection and exit'
complete -c xapian-replicate-server -l help -d 'display this help and exit'
complete -c xapian-replicate-server -l version -d 'output version information and exit'

