# xapian-config
# Autogenerated from man page /usr/share/man/man1/xapian-config.1.gz
complete -c xapian-config -l cxxflags -d 'output all preprocessor and C++ compiler flags'
complete -c xapian-config -l libs -d 'output all linker flags'
complete -c xapian-config -l ltlibs -d 'output linker flags for linking using GNU libtool'
complete -c xapian-config -l static -d 'make other options report values for static linking'
complete -c xapian-config -l swigflags -d 'output preprocessor flags for use with SWIG'
complete -c xapian-config -l help -d 'output this help and exit'
complete -c xapian-config -l version -d 'output version information and exit REPORTING BUGS Report bugs to <https://xa…'

