#!/bin/bash

# if [ $(pgrep -c power-menu) ]; then
  # exec pkill power-menu
# else
  # exec /home/me/.local/src/personal/utils/power/power-menu
# fi

pkill power-menu || exec /home/me/.local/src/personal/utils/power/power-menu


